# This is a sample configuration for the Aye-Aye Sleep Monitoring Data Server.
# Use this as a basis for configuring the data server for the specific server.

# Local path in which to store the data hierarchy
data_dir: /home/asm-data/nas/data

# This is the primary port for the data server.
port: 9000

# Data Server UID
#
# This is the UUID that uniquely identifies this device.
server_uuid: "fda6297c-1107-11ec-bbd2-fcaa14694a7a"

# This is the maximum length of video data
video_increment: 300

# RTSP Server Port Block
#
# This is the block of ports that RTSP servers should use.
rtsp_port_block: [9100, 9200]

# The amount of time in senconds for a device to be considered dropped
# without hearing a heartbeat
heartbeat_timeout_secs: 10.0

# This is the account of email sender.
email_username: "YOUR EMAIL ACCOUNT"

# This is the password pf email sender.
email_password: "YOUR EMAIL PASSWORD"

# This is the list of Admins email account that will receive the email.
eamil_receiver: ['zhz049@ucsd.edu']

# This is the sample email subject.
email_subject: "Node unconnected"

# This is the sample email content
email_content: "Node is unconnected from data server"
